import HTMLHead from 'next/head'

const Head = () => {
  return (
    <HTMLHead>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </HTMLHead>
  )
}

export default Head
